#!/usr/bin/env node

/**
 * Test Case Generator for CodeRabbit
 * Automatically generates test cases for new functions
 */

const fs = require('fs');
const path = require('path');

// Get changed files from git
function getChangedFiles() {
  try {
    const { execSync } = require('child_process');
    const output = execSync('git diff --name-only HEAD~1', { encoding: 'utf8' });
    return output.trim().split('\n').filter(file => file.endsWith('.js') || file.endsWith('.ts'));
  } catch (error) {
    console.log('No previous commit found, checking all JS/TS files');
    return getAllSourceFiles();
  }
}

// Get all source files
function getAllSourceFiles() {
  const files = [];
  function scanDir(dir) {
    const items = fs.readdirSync(dir);
    for (const item of items) {
      const fullPath = path.join(dir, item);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory() && !['node_modules', 'dist', 'build', '.git'].includes(item)) {
        scanDir(fullPath);
      } else if (stat.isFile() && (item.endsWith('.js') || item.endsWith('.ts'))) {
        files.push(fullPath);
      }
    }
  }
  scanDir('.');
  return files;
}

// Parse JavaScript/TypeScript file for functions
function parseFileForFunctions(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const functions = [];

  // Simple regex to find function declarations and arrow functions
  const functionRegex = /(?:function\s+(\w+)|(?:const|let|var)\s+(\w+)\s*=\s*(?:\([^)]*\)\s*=>|function))/g;
  let match;

  while ((match = functionRegex.exec(content)) !== null) {
    const functionName = match[1] || match[2];
    if (functionName && !functions.includes(functionName)) {
      functions.push(functionName);
    }
  }

  return functions;
}

// Generate test file for a source file
function generateTestFile(sourceFile, functions) {
  const testFile = sourceFile.replace(/\.js$|\.ts$/, '.test.js');
  const relativePath = path.relative('.', sourceFile);
  const moduleName = path.basename(sourceFile, path.extname(sourceFile));

  let testContent = `/**
 * Test cases for ${relativePath}
 * Auto-generated by CodeRabbit
 */

const ${moduleName} = require('./${relativePath.replace(/\\/g, '/').replace(/\.ts$/, '.js')}');

describe('${moduleName}', () => {
`;

  for (const func of functions) {
    testContent += `
  describe('${func}', () => {
    test('should be defined', () => {
      expect(${moduleName}.${func}).toBeDefined();
    });

    test('should handle valid input', () => {
      // TODO: Add specific test cases based on function signature
      expect(() => ${moduleName}.${func}()).not.toThrow();
    });

    test('should handle edge cases', () => {
      // TODO: Add edge case tests
      expect(true).toBe(true); // Placeholder
    });
  });
`;
  }

  testContent += `
  // Integration tests
  describe('Integration Tests', () => {
    test('should work end-to-end', () => {
      // TODO: Add integration test
      expect(true).toBe(true);
    });
  });
});

module.exports = ${moduleName};
`;

  // Create test directory if it doesn't exist
  const testDir = path.dirname(testFile);
  if (!fs.existsSync(testDir)) {
    fs.mkdirSync(testDir, { recursive: true });
  }

  fs.writeFileSync(testFile, testContent);
  console.log(`✅ Generated test file: ${testFile}`);
}

// Main execution
function main() {
  console.log('🔍 Analyzing changed files for test generation...');

  const changedFiles = getChangedFiles();
  console.log(`Found ${changedFiles.length} changed files`);

  for (const file of changedFiles) {
    if (fs.existsSync(file)) {
      const functions = parseFileForFunctions(file);
      if (functions.length > 0) {
        console.log(`📝 Generating tests for ${file} (${functions.length} functions)`);
        generateTestFile(file, functions);
      }
    }
  }

  console.log('✅ Test generation completed');
}

// Run if called directly
if (require.main === module) {
  main();
}

module.exports = { main, parseFileForFunctions, generateTestFile };